apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: circleci-express
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 3000
  selector:
    app: circleci-express
    tier: frontend
